### ISSUE TITLE
week 01 回饋

### ISSUE THREAD

**Issue by azole** [Esther125/git-practice#1]
鼓勵你透過這門課練習對技術的深入研究能力，你試著把我在作業單上提出的問題當作起點，而不是探索的終點，例如，你在嘗試研究 & 回答完作業單上的問題後，又對 .git 檔案夾做了觀察，那你自己有沒有產生什麼新的問題與想法？

試著對技術、對自己在用的東西，有更多的好奇心看看。

**Comment by Esther125** [comment]
我了解了，謝謝老師！

**Comment by azole** [comment]
謝謝你的回覆，這個 issue 可以 close 了。
